export const priceData_A = [
  {
    id: '1a',
    title: 'Starter',
    para: 'Ideal for freelancers and contractors just starting out.',
    price: 24,
    items: [
      'All Templates',
      'Unlimited Clients & Projects',
      'Invoicing & Payments',
      'Proposals & Contracts',
      'Tasks & Time Tracking',
      'Client CRM',
      'Expense Tracking',
      'Up to 5 Project Collaborators',
    ],
    billed: false,
  },
  {
    id: '2a',
    title: 'Professional',
    para: 'Everything a growing independent business needs to thrive.',
    price: 39,
    items: [
      'Everything in Starter plus...',
      'Custom Branding',
      'Forms & Questionnaires',
      'Workflow Automations',
      'Client Portal',
      'QuickBooks Integration',
      'Calendly Integration',
      'Zapier Integration',
      'Up to 15 Project Collaborators',
    ],
    billed: false,
  },
  {
    id: '3a',
    title: 'Business',
    para: 'The perfect package for small businesses and agencies.',
    price: 79,
    items: [
      'Everything in Starter and Professional plus...',
      'Subcontractor Management',
      'Hiring Agreement Templates (1099 contracts)',
      'Subcontractor Onboarding',
      'Talent Pool',
      '3 Team Seats (additional seats $9/month)',
      'Accountant Access',
      'Connect Multiple Bank Accounts',
      'Unlimited Subcontractors',
      'Unlimited Project Collaborators',
    ],
    billed: false,
  },
];

export const priceData_B = [
  {
    id: '1a',
    title: 'Starter',
    para: 'Ideal for freelancers and contractors just starting out.',
    price: 17,
    items: [
      'All Templates',
      'Unlimited Clients & Projects',
      'Invoicing & Payments',
      'Proposals & Contracts',
      'Tasks & Time Tracking',
      'Client CRM',
      'Expense Tracking',
      'Up to 5 Project Collaborators',
    ],
    billed: true,
  },
  {
    id: '2a',
    title: 'Professional',
    para: 'Everything a growing independent business needs to thrive.',
    price: 32,
    items: [
      'Everything in Starter plus...',
      'Custom Branding',
      'Forms & Questionnaires',
      'Workflow Automations',
      'Client Portal',
      'Calendly Integration',
      'Zapier Integration',
      'Up to 15 Project Collaborators',
    ],
    billed: true,
  },
  {
    id: '3a',
    title: 'Business',
    para: 'The perfect package for small businesses and agencies.',
    price: 52,
    items: [
      'Everything in Starter and Professional plus...',
      'Subcontractor Management',
      'Hiring Agreement Templates (1099 contracts)',
      'Subcontractor Onboarding',
      'Talent Pool',
      '3 Team Seats (additional seats $9/month)',
      'Accountant Access',
      'Connect Multiple Bank Accounts',
      'Unlimited Subcontractors',
      'Unlimited Project Collaborators',
    ],
    billed: true,
  },
];
