export const footGroups = [
  [
    { name: 'PRODUCT' },
    { name: 'Proposals', path: '/proposals' },
    { name: 'Contracts', path: '/contracts' },
    { name: 'Invoicing', path: '/invoicing' },
    { name: 'Client CRM', path: '/client-crm' },
    { name: 'Time Tracking', path: '/time-tracking' },
    { name: 'Task Tracking', path: '/task-tracking' },
    { name: 'Forms', path: '/freelance-form' },
    { name: 'Accounting', path: '/accounting' },
    { name: 'Bonsai Tax', path: '/bonsai-tax' },
    { name: 'Bonsai Cash', path: '/bonsai-cash', style: true },
    { name: 'Pricing', path: '/pricings' },
    { name: 'Bonsai Reviews', path: '/reviews' },
  ],
  [
    { name: 'FREE RESOURCES' },
    { name: 'Freelance Resources', path: '/' },
    { name: 'Freelance Blog by Bonsai', path: '/' },
    { name: 'How to Write a Contract', path: '/' },
    { name: 'Online Signature Maker', path: '/', style: true },
    { name: 'Self-Employed Taxes Hub', path: '/' },
    { name: 'Self-Employed Tax Calculator', path: '/' },
    { name: 'Self-Employed Tax Deductions', path: '/', style: true },
    { name: 'Templates' },
    { name: 'Invoice Templates', path: '/', arrow: true },
    { name: 'Contract Templates', path: '/', arrow: true },
  ],
  [
    { name: 'BONSAI' },
    { name: 'About', path: '/' },
    { name: 'Careers', path: '/' },
    { name: 'Support', path: '/' },
    { name: 'LinkedIn', path: '/' },
    { name: 'Twitter', path: '/' },
    { name: 'Privacy policy', path: '/' },
    { name: 'Legal', path: '/', style: true },
    { name: 'Affiliates', path: '/' },
    { name: 'Write for Us', path: '/' },
  ],
];
